[{
	"version": null,
	"description": "<p><strong> 超强支撑，统御全场。</strong><br/><br/><strong>TCC</strong> 配色<br/>TCC配色所代表的信任、关怀与承诺，传承自库里母校的精神，团队的胜利是他唯一追求的目标。</p><div class='descr-text'><div><span>科技介绍</span><ul><li>Meta-Wing碳纤维足弓有助改善整个脚掌的稳定性，并有助减少滑动</li><li>Anafoam材质带来舒适贴合、轻质结构与稳固支撑</li><li>Charged Cushioning中底科技，带来迅疾的启动变向</li></ul></div><div><span>商品细节</span><ul><li>织纹鞋面有助改善足部运动灵活性，为篮球高手提供支持</li><li>根据44码检测单只重量约388克，不同尺码会有相应差异</li></ul></div><div><span>适合运动</span><ul><li>适合篮球等运动</li></ul></div></div>",
	"lifecycle": 1,
	"code": "1269279-600",
	"seoTitle": "男士UA Curry 3篮球鞋【正品|价格|图片】-Under Armour|安德玛中国官网",
	"seoKeywords": "男士UA Curry 3篮球鞋正品，男士UA Curry 3篮球鞋价格，男士UA Curry 3篮球鞋TCC||Curry3||库里3||库里3代||库里三||库里三代||currythree图片",
	"seoDescription": "安德玛（UA）中国官网，在线购买男士UA Curry 3篮球鞋正品，同时为您提供男士UA Curry 3篮球鞋价格、图片等信息，选购专业运动装备就到under armour中国官网。",
	"modifyTime": null,
	"createTime": null,
	"shopId": null,
	"isDefault": null,
	"picUrl": null,
	"title": "男士UA Curry 3篮球鞋",
	"sketch": "",
	"subTitle": "线上专供配色！下单后30分钟内未付款，订单将自动取消，请您尽快完成支付！",
	"listTime": 1480650134620,
	"industryId": "1",
	"salePrice": 1299.00,
	"listPrice": 1299.00,
	"industryName": null,
	"style": "1269279",
	"activeBeginTime": 1481335200000,
	"activeEndTime": null,
	"jsonSku": null,
	"categoryNames": null,
	"categoryCodes": null,
	"tagNames": null,
	"channels": null,
	"additionalAttributes": null,
	"itemUrl": null,
	"rankavg": null,
	"salesCount": null,
	"itemImageList": null,
	"imageCount": null,
	"suitItem": null,
	"defCategory": null,
	"defCategroyId": null,
	"id": 15993,
	"type": 1
}, {
	"version": null,
	"description": "<p><strong>超强支撑，统御全场。</strong></p><div class='descr-text'><div><span>科技介绍</span><ul><li>Meta-Wing碳纤维足弓有助改善整个脚掌的稳定性，并有助减少滑动</li><li>Anafoam材质带来舒适贴合、轻质结构与稳固支撑</li><li>Charged Cushioning中底科技，带来迅疾的启动变向</li></ul></div><div><span>商品细节</span><ul><li>织纹鞋面有助改善足部运动灵活性，为篮球高手提供支持</li><li>根据44码检测单只重量约388克，不同尺码会有相应差异</li></ul></div><div><span>适合运动</span><ul><li>适合篮球等运动</li></ul></div></div>",
	"lifecycle": 1,
	"code": "1269279-458",
	"seoTitle": "男士UA Curry 3篮球鞋【正品|价格|图片】-Under Armour|安德玛中国官网",
	"seoKeywords": "男士UA Curry 3篮球鞋正品，男士UA Curry 3篮球鞋价格，男士UA Curry 3篮球鞋Curry3||库里3||库里3代||库里三||库里三代||currythree图片",
	"seoDescription": "安德玛（UA）中国官网,在线购买男士UA Curry 3篮球鞋正品，同时为您提供男士UA Curry 3篮球鞋价格、图片等信息，选购专业运动装备就到under armour中国官网。",
	"modifyTime": null,
	"createTime": null,
	"shopId": null,
	"isDefault": null,
	"picUrl": null,
	"title": "男士UA Curry 3篮球鞋",
	"sketch": "",
	"subTitle": "下单后30分钟内未付款，订单将自动取消，请您尽快完成支付！",
	"listTime": 1491450893945,
	"industryId": "1",
	"salePrice": 1299.00,
	"listPrice": 1299.00,
	"industryName": null,
	"style": "1269279",
	"activeBeginTime": 1491616800000,
	"activeEndTime": null,
	"jsonSku": null,
	"categoryNames": null,
	"categoryCodes": null,
	"tagNames": null,
	"channels": null,
	"additionalAttributes": null,
	"itemUrl": null,
	"rankavg": null,
	"salesCount": null,
	"itemImageList": null,
	"imageCount": null,
	"suitItem": null,
	"defCategory": null,
	"defCategroyId": null,
	"id": 16214,
	"type": 1
}, {
	"version": null,
	"description": "<p></p><div class='descr-text'><div><span>科技介绍</span><ul><li>“Burrito tongue”鞋舌构造紧裹双足，舒适合脚，有助于使行动灵活自如</li><li>全掌注塑Micro G鞋垫贴合足底</li><li>Micro G发泡材料中底提供落地缓冲的同时有助于将能量转化为有力反弹</li></ul></div><div><span>商品细节</span><ul><li>轻质皮革鞋面，柔韧性良好</li><li>注塑发泡材料鞋帮紧裹踝部，有助于从而有助于改善贴合度，舒适支撑</li><li>鞋身上精心设计的孔眼结构有助于增强透气通风</li><li>饰有大号UA logo标牌</li><li>结实的一体式橡胶外底，人字纹设计有助增强牵引力，从而有助于改善移动灵活性，强化双足控制</li><li>根据44码检测单只重量约388g，不同尺码会有相应差异</li></ul></div><div><span>适合运动</span><ul><li>适合篮球等运动</li></ul></div></div>",
	"lifecycle": 1,
	"code": "1286385-002",
	"seoTitle": "男士UA Rocket 2篮球鞋【正品|价格|图片】-Under Armour|安德玛中国官网",
	"seoKeywords": "男士UA Rocket 2篮球鞋正品，男士UA Rocket 2篮球鞋价格，男士UA Rocket 2篮球鞋图片",
	"seoDescription": "安德玛（UA）中国官网,在线购买男士UA Rocket 2篮球鞋正品，同时为您提供男士UA Rocket 2篮球鞋价格、图片等信息，选购专业运动装备就到under armour中国官网。",
	"modifyTime": null,
	"createTime": null,
	"shopId": null,
	"isDefault": null,
	"picUrl": null,
	"title": "男士UA Rocket 2篮球鞋",
	"sketch": null,
	"subTitle": null,
	"listTime": 1494938952888,
	"industryId": "1",
	"salePrice": 799.00,
	"listPrice": 799.00,
	"industryName": null,
	"style": "1286385",
	"activeBeginTime": null,
	"activeEndTime": null,
	"jsonSku": null,
	"categoryNames": null,
	"categoryCodes": null,
	"tagNames": null,
	"channels": null,
	"additionalAttributes": null,
	"itemUrl": null,
	"rankavg": null,
	"salesCount": null,
	"itemImageList": null,
	"imageCount": null,
	"suitItem": null,
	"defCategory": null,
	"defCategroyId": null,
	"id": 17132,
	"type": 1
}, {
	"version": null,
	"description": "<p></p><div class='descr-text'><div><span>科技介绍</span><ul><li>“Burrito tongue”鞋舌构造紧裹双足，舒适合脚，有助于使行动灵活自如</li><li>全掌注塑Micro G鞋垫贴合足底</li><li>Micro G发泡材料中底提供落地缓冲的同时有助于将能量转化为有力反弹</li></ul></div><div><span>商品细节</span><ul><li>轻质皮革鞋面，柔韧性良好</li><li>注塑发泡材料鞋帮紧裹踝部，有助于从而有助于改善贴合度，舒适支撑</li><li>鞋身上精心设计的孔眼结构有助于增强透气通风</li><li>饰有大号UA logo标牌</li><li>结实的一体式橡胶外底，人字纹设计有助增强牵引力，从而有助于改善移动灵活性，强化双足控制</li><li>根据44码检测单只重量约388g，不同尺码会有相应差异</li></ul></div><div><span>适合运动</span><ul><li>适合篮球等运动</li></ul></div></div>",
	"lifecycle": 1,
	"code": "1286385-001",
	"seoTitle": "男士UA Rocket 2篮球鞋【正品|价格|图片】-Under Armour|安德玛中国官网",
	"seoKeywords": "男士UA Rocket 2篮球鞋正品，男士UA Rocket 2篮球鞋价格，男士UA Rocket 2篮球鞋图片",
	"seoDescription": "安德玛（UA）中国官网,在线购买男士UA Rocket 2篮球鞋正品，同时为您提供男士UA Rocket 2篮球鞋价格、图片等信息，选购专业运动装备就到under armour中国官网。",
	"modifyTime": null,
	"createTime": null,
	"shopId": null,
	"isDefault": null,
	"picUrl": null,
	"title": "男士UA Rocket 2篮球鞋",
	"sketch": null,
	"subTitle": null,
	"listTime": 1487847880885,
	"industryId": "1",
	"salePrice": 799.00,
	"listPrice": 799.00,
	"industryName": null,
	"style": "1286385",
	"activeBeginTime": null,
	"activeEndTime": null,
	"jsonSku": null,
	"categoryNames": null,
	"categoryCodes": null,
	"tagNames": null,
	"channels": null,
	"additionalAttributes": null,
	"itemUrl": null,
	"rankavg": null,
	"salesCount": null,
	"itemImageList": null,
	"imageCount": null,
	"suitItem": null,
	"defCategory": null,
	"defCategroyId": null,
	"id": 17560,
	"type": 1
}, {
	"version": null,
	"description": "<p><strong>超强支撑，统御全场。</strong></p><div class='descr-text'><div><span>科技介绍</span><ul><li>Meta-Wing碳纤维足弓有助改善整个脚掌的稳定性，并有助减少滑动</li><li>Anafoam材质带来舒适贴合、轻质结构与稳固支撑</li><li>Charged Cushioning中底科技，带来迅疾的启动变向</li></ul></div><div><span>商品细节</span><ul><li>织纹鞋面有助改善足部运动灵活性，为篮球高手提供支持</li><li>根据44码检测单只重量约388克，不同尺码会有相应差异</li></ul></div><div><span>适合运动</span><ul><li>适合篮球等运动</li></ul></div></div>",
	"lifecycle": 1,
	"code": "1269279-106",
	"seoTitle": "男士UA Curry 3篮球鞋【正品|价格|图片】-Under Armour|安德玛中国官网",
	"seoKeywords": "男士UA Curry 3篮球鞋正品，男士UA Curry 3篮球鞋价格，Curry3||库里3||库里3代||库里三||库里三代||currythree图片",
	"seoDescription": "安德玛（UA）中国官网,在线购买男士UA Curry 3篮球鞋正品，同时为您提供男士UA Curry 3篮球鞋价格、图片等信息，选购专业运动装备就到under armour中国官网。",
	"modifyTime": null,
	"createTime": null,
	"shopId": null,
	"isDefault": null,
	"picUrl": null,
	"title": "男士UA Curry 3篮球鞋",
	"sketch": null,
	"subTitle": "下单后30分钟内未付款，订单将自动取消，请您尽快完成支付！",
	"listTime": 1495614595426,
	"industryId": "1",
	"salePrice": 1299.00,
	"listPrice": 1299.00,
	"industryName": null,
	"style": "1269279",
	"activeBeginTime": 1489456800000,
	"activeEndTime": null,
	"jsonSku": null,
	"categoryNames": null,
	"categoryCodes": null,
	"tagNames": null,
	"channels": null,
	"additionalAttributes": null,
	"itemUrl": null,
	"rankavg": null,
	"salesCount": null,
	"itemImageList": null,
	"imageCount": null,
	"suitItem": null,
	"defCategory": null,
	"defCategroyId": null,
	"id": 17292,
	"type": 1
}, {
	"version": null,
	"description": "<p></p><div class='descr-text'><div><span>科技介绍</span><ul><li>UA ClutchFit Force 3.0足球鞋，为球场上技艺精巧、视野开阔、跑位灵动的节奏掌控者而生</li><li>高性能Trivela细腻纤维鞋面紧裹脚掌，有助于舒适贴合</li><li>在前代产品基础上经过改良、贴合度进一步提升的中足与前足构造，有助于让ClutchFit鞋面在多种场地条件下充分发挥触球精度高的优势</li><li>Charged Cushioning鞋垫有助于吸收冲击并转化为有力反弹</li><li>BZM内足弓有助强化支撑，有助于改善减速性能，灵活的前足设计有助提高加速性能</li></ul></div><div><span>商品细节</span><ul><li>后跟处的防滑材料有助于改善牵引力与贴合度</li><li>钉底设计，有助于实现与足部的自然运动相适应</li><li>根据43码检测单只重量约292g，不同尺码会有相应差异</li></ul></div><div><span>适合运动</span><ul><li>适合足球等运动</li></ul></div><div><span>适合场地</span><ul><li>适合天然草地</li></ul></div></div>",
	"lifecycle": 1,
	"code": "1278817-100",
	"seoTitle": "男士UA ClutchFit Force 3.0 FG足球鞋【正品|价格|图片】-Under Armour|安德玛中国官网",
	"seoKeywords": "男士UA ClutchFit Force 3.0 FG足球鞋正品，男士UA ClutchFit Force 3.0 FG足球鞋价格，男士UA ClutchFit Force 3.0 FG足球鞋图片",
	"seoDescription": "安德玛（UA）中国官网,在线购买男士UA ClutchFit Force 3.0 FG足球鞋正品，同时为您提供男士UA ClutchFit Force 3.0 FG足球鞋价格、图片等信息，选购专业运动装备就到under armour中国官网。",
	"modifyTime": null,
	"createTime": null,
	"shopId": null,
	"isDefault": null,
	"picUrl": null,
	"title": "男士UA ClutchFit Force 3.0 FG足球鞋",
	"sketch": null,
	"subTitle": null,
	"listTime": 1487847880885,
	"industryId": "1",
	"salePrice": 1799.00,
	"listPrice": 1799.00,
	"industryName": null,
	"style": "1278817",
	"activeBeginTime": null,
	"activeEndTime": null,
	"jsonSku": null,
	"categoryNames": null,
	"categoryCodes": null,
	"tagNames": null,
	"channels": null,
	"additionalAttributes": null,
	"itemUrl": null,
	"rankavg": null,
	"salesCount": null,
	"itemImageList": null,
	"imageCount": null,
	"suitItem": null,
	"defCategory": null,
	"defCategroyId": null,
	"id": 16489,
	"type": 1
}, {
	"version": null,
	"description": "<p><strong>Run Long</strong> - 舒适支撑，为那些寻找卓越舒适度并想跑得更远的跑者而设计。</p><div class='descr-text'><div><span>科技介绍</span><ul><li>以Bemis贴带结合平滑的超声波缝合工艺，有助于紧贴并保护双脚，带来不凡的舒适感受</li><li>注模Micro G鞋垫有助于贴合脚掌自然形状，从而有助于提升缓冲性与贴合度</li><li>两片式charged cushioning中底后跟处硬实、前足处相比后跟处较软，有助于改善舒适度与支撑性并提升性能</li></ul></div><div><span>商品细节</span><ul><li>紧致内靴设计紧裹双足，建议购买大半码</li><li>杂色鞋面轻质、透气、弹性良好</li><li>无缝鞋跟垫紧锁双足，有助于实现舒适合脚</li><li>结实的外足跟垫有助于强化支撑，有助减少足跟滑动</li><li>新颖的鞋舌构造与鞋面相连，贴合脚面，有助减少滑动</li><li>橡胶外底有助于提供充分的触地体验，弯曲凹槽为需要的区域提供足够的灵活度</li><li>后跟处高磨损区域所使用的抗磨橡胶增加耐久性</li><li>掌跟差：10mm</li><li>根据46码检测单只重量约322克，不同尺码会有相应差异</li></ul></div><div><span>适合运动</span><ul><li>适合跑步等运动</li></ul></div></div>",
	"lifecycle": 1,
	"code": "1273951-077",
	"seoTitle": "男士UA Charged Bandit 2跑鞋【正品|价格|图片】-Under Armour|安德玛中国官网",
	"seoKeywords": "男士UA Charged Bandit 2跑鞋正品，男士UA Charged Bandit 2跑鞋价格，男士UA Charged Bandit 2跑鞋bandit2图片",
	"seoDescription": "安德玛（UA）中国官网,在线购买男士UA Charged Bandit 2跑鞋正品，同时为您提供男士UA Charged Bandit 2跑鞋价格、图片等信息，选购专业运动装备就到under armour中国官网。",
	"modifyTime": null,
	"createTime": null,
	"shopId": null,
	"isDefault": null,
	"picUrl": null,
	"title": "男士UA Charged Bandit 2跑鞋",
	"sketch": null,
	"subTitle": null,
	"listTime": 1491806661915,
	"industryId": "1",
	"salePrice": 899.00,
	"listPrice": 899.00,
	"industryName": null,
	"style": "1273951",
	"activeBeginTime": null,
	"activeEndTime": null,
	"jsonSku": null,
	"categoryNames": null,
	"categoryCodes": null,
	"tagNames": null,
	"channels": null,
	"additionalAttributes": null,
	"itemUrl": null,
	"rankavg": null,
	"salesCount": null,
	"itemImageList": null,
	"imageCount": null,
	"suitItem": null,
	"defCategory": null,
	"defCategroyId": null,
	"id": 16266,
	"type": 1
}, {
	"version": null,
	"description": "<p><strong>Run Long</strong> -为长跑者而设计，提供卓越的舒适度。优质缓震，快速反应。</p><div class='descr-text'><div><span>科技介绍</span><ul><li>新颖的UA SpeedForm构造，贴合脚面，有助减少穿着不适感</li><li>Charged Cushioning中底利用压缩发泡材料，弹力与耐用度良好，能够有效缓震与反弹</li><li>Micro G后跟设计有助于强化保护与稳定性</li><li>Threadborne织纹中足镶面，优化结构，凸显时尚风格</li></ul></div><div><span>商品细节</span><ul><li>鞋舌与鞋头处精心设计的网眼层有助改善贴合度与透气性</li><li>内部后跟承托架轻质舒适，有助改善结构与支撑</li><li>嵌入式鞋垫加强缓冲，有助改善支撑，提升舒适度</li><li>前足底部的发泡橡胶区域轻质舒适，弹性出色</li><li>后跟底部的高耐磨橡胶有助于吸收来自地面的冲击</li><li>掌跟差：8毫米</li><li>根据44码检测单只重量约 300 g，不同尺码会有相应差异</li></ul></div><div><span>适合运动</span><ul><li>适合跑步等运动</li></ul></div></div><br/><p><a href=\"javascript:openV('8E7C51B6835D04B79C33DC5901307461','true');\" style=\"cursor:pointer\" target=\"_blank\"><img src=\"https://resource.underarmour.cn/resources/images/PDP-Video/PC-PDP-VIDEO-221x140-GEMINI3_20170523191544.jpg\" /></a></p>",
	"lifecycle": 1,
	"code": "1285652-076",
	"seoTitle": "男士UA SpeedForm Gemini 3跑鞋【正品|价格|图片】-Under Armour|安德玛中国官网",
	"seoKeywords": "男士UA SpeedForm Gemini 3跑鞋正品，男士UA SpeedForm Gemini 3跑鞋价格，男士UA SpeedForm Gemini 3跑鞋跑出色||Run The Spectrum||Space Program||Gemini3||全新功能跑鞋图片",
	"seoDescription": "安德玛（UA）中国官网,在线购买男士UA SpeedForm Gemini 3跑鞋正品，同时为您提供男士UA SpeedForm Gemini 3跑鞋价格、图片等信息，选购专业运动装备就到under armour中国官网。",
	"modifyTime": null,
	"createTime": null,
	"shopId": null,
	"isDefault": null,
	"picUrl": null,
	"title": "男士UA SpeedForm Gemini 3跑鞋",
	"sketch": null,
	"subTitle": null,
	"listTime": 1495614595426,
	"industryId": "1",
	"salePrice": 1099.00,
	"listPrice": 1099.00,
	"industryName": null,
	"style": "1285652",
	"activeBeginTime": null,
	"activeEndTime": null,
	"jsonSku": null,
	"categoryNames": null,
	"categoryCodes": null,
	"tagNames": null,
	"channels": null,
	"additionalAttributes": null,
	"itemUrl": null,
	"rankavg": null,
	"salesCount": null,
	"itemImageList": null,
	"imageCount": null,
	"suitItem": null,
	"defCategory": null,
	"defCategroyId": null,
	"id": 17018,
	"type": 1
}]